### PR TITLE
[Stylelint] Normalize windows and canonical paths

### PR DESCRIPTION
**Pull request by henryruhs**

### CODE REVIEW

**Comment by henryruhs** [comment]
This should fix Windows but I could not verify it. The CI pipeline is too complex complicated and heavily depends on unix commands. I gave up after spending like 2h to get it running - we need different approaches like `npm link` over `npm pack`, no passing of env between steps, usage of nodejs powered tooling like `cpy-cli`and `del-cli`and finally compare against a `result.txt` that commited to the version control instead of using `grep`commands.

**Comment by krema** [comment]
Thanks for initiating the windows stylelint issue fix. I forgot it already.

To make your intended solution/PR work and testable I added a commit.

> we need different approaches like npm link over npm pack

**npm link** will not work in our case. We need peer dependency resolvement. 

> no passing of env between steps

don't see a reason or problem not to do that

> usage of nodejs powered tooling like cpy-cliand del-cli

no need!

> finally compare against a result.txt that commited to the version control instead of using grep commands.

Didn't understand your statement why grep is not a valid solution

**Comment by krema** [comment]
- cleaned up your commits and made your commit message conventional
- removed the mac platform as a runner is hardly available

**Pull request merged**
